"""
Aggregates endpoint (blocking).

Generated by spitzeisen-gen from spec/manifest.yaml. Do not edit; run `mise run codegen`.

Vendor documentation: https://massive.com/docs/rest/stocks/aggregates/custom-bars

"""

from datetime import date, datetime
from typing import Any, Literal

from spitzeisen import (
    BaseApi,
    EndpointSpec,
    NoPagination,
    build_query_params,
    coerce_choice,
    coerce_date,
    coerce_max_results,
    resolve_page_size,
)

from massive_api.models import Bar, Order, Timespan

AGGREGATES_ENDPOINT = EndpointSpec(
    path="/v2/aggs/ticker/{stocksTicker}/range/{multiplier}/{timespan}/{from}/{to}",
    costs={"requests": 1.0},
    pagination=NoPagination(results_key="results"),
    max_page_size=50000,
)


class AggregatesApiSyncBase(BaseApi):
    """
    Generated request layer for the aggregates endpoint.

    Subclassed by `AggregatesApiSync`, which is where any hand-written behaviour
    belongs — this class is regenerated and never edited.
    """

    def get_custom_bars_raw(
        self,
        ticker: str,
        multiplier: int,
        timespan: Timespan,
        from_date: str | date | datetime,
        to_date: str | date | datetime,
        *,
        adjusted: bool | None = None,
        order: Order | None = None,
        max_results: int | None = None,
    ) -> list[dict[str, Any]]:
        """
        Fetch aggregates as raw JSON dicts, without validation.

        See `get_custom_bars` for what each argument means.
        """
        max_results = coerce_max_results(max_results)
        params = build_query_params(
            {
                "adjusted": adjusted,
                "sort": coerce_choice(order, Order, "order"),
                "limit": resolve_page_size(max_results, 50000),
            },
        )
        return self._get_all_pages(
            AGGREGATES_ENDPOINT,
            params,
            max_results=max_results,
            **{
                "stocksTicker": ticker,
                "multiplier": multiplier,
                "timespan": coerce_choice(timespan, Timespan, "timespan"),
                "from": coerce_date(from_date, "from_date"),
                "to": coerce_date(to_date, "to_date"),
            },
        )

    def get_custom_bars(
        self,
        ticker: str,
        multiplier: int,
        timespan: Timespan,
        from_date: str | date | datetime,
        to_date: str | date | datetime,
        *,
        adjusted: bool | None = None,
        order: Order | None = None,
        max_results: int | None = None,
        on_validation_error: Literal["raise", "skip"] | None = None,
    ) -> list[Bar]:
        """
        Get custom OHLCV aggregate bars for a ticker, validated into `Bar` models.

        Blocks until every page is fetched, then validates the records that came back.

        Docs: https://massive.com/docs/rest/stocks/aggregates/custom-bars

        Example::

            with MassiveApiSync(api_key="...") as api:
                results = api.aggregates_api.get_custom_bars()

        Args:
            ticker: Specify a case-sensitive ticker symbol. For example, AAPL represents Apple Inc.
            multiplier: Size of the timespan multiplier (e.g. 1 for 1-day bars).
            timespan: The size of the time window.
            from_date: The start of the aggregate time window. Either a date with the format YYYY-MM-DD or a
                millisecond timestamp.
            to_date: The end of the aggregate time window. Either a date with the format YYYY-MM-DD or a millisecond
                timestamp.
            adjusted: Whether or not the results are adjusted for splits. By default, results are adjusted. Set this
                to false to get results that are NOT adjusted for splits.
            order: Sort direction for the returned bars.
            max_results: Maximum total records to return (None means no cap).
            on_validation_error: Override the config default ("raise" or "skip") for this call.

        Returns:
            A list of `Bar`, at most `max_results` long.

        Raises:
            ValueError: If an argument is outside the values the API accepts.
            MaxRetriesExceededError: If rate-limit responses persist past `max_retries`.

        """
        records = self.get_custom_bars_raw(
            ticker,
            multiplier,
            timespan,
            from_date,
            to_date,
            adjusted=adjusted,
            order=order,
            max_results=max_results,
        )
        return self._validate_records(records, Bar, self._resolve_validation_mode(on_validation_error))
