"""
Dividends endpoint (blocking).

Generated by spitzeisen-gen from spec/manifest.yaml. Do not edit; run `mise run codegen`.

Vendor documentation: https://massive.com/docs/rest/stocks/corporate-actions/dividends

"""

from datetime import date, datetime
from typing import Any, Literal

from spitzeisen import (
    BaseApi,
    CursorUrl,
    EndpointSpec,
    build_query_params,
    coerce_choice,
    coerce_choices,
    coerce_date,
    coerce_max_results,
    coerce_sort,
    resolve_page_size,
)

from massive_api.models import DistributionType, Dividend, DividendFrequency

DIVIDENDS_ENDPOINT = EndpointSpec(
    path="/stocks/v1/dividends",
    costs={"requests": 1.0},
    pagination=CursorUrl(results_key="results"),
    max_page_size=5000,
)


class DividendsApiSyncBase(BaseApi):
    """
    Generated request layer for the dividends endpoint.

    Subclassed by `DividendsApiSync`, which is where any hand-written behaviour
    belongs — this class is regenerated and never edited.
    """

    def get_dividends_raw(
        self,
        *,
        ticker: str | None = None,
        tickers: list[str] | None = None,
        ticker_gt: str | None = None,
        ticker_gte: str | None = None,
        ticker_lt: str | None = None,
        ticker_lte: str | None = None,
        ex_dividend_date: str | date | datetime | None = None,
        ex_dividend_date_gt: str | date | datetime | None = None,
        ex_dividend_date_gte: str | date | datetime | None = None,
        ex_dividend_date_lt: str | date | datetime | None = None,
        ex_dividend_date_lte: str | date | datetime | None = None,
        frequency: DividendFrequency | None = None,
        frequency_gt: int | None = None,
        frequency_gte: int | None = None,
        frequency_lt: int | None = None,
        frequency_lte: int | None = None,
        distribution_types: list[DistributionType] | None = None,
        max_results: int | None = None,
        sort: Literal["ticker", "ex_dividend_date", "frequency", "distribution_type"] = "ticker",
        order: Literal["asc", "desc"] = "asc",
    ) -> list[dict[str, Any]]:
        """
        Fetch dividends as raw JSON dicts, without validation.

        See `get_dividends` for what each argument means.
        """
        max_results = coerce_max_results(max_results)
        params = build_query_params(
            {
                "ticker": ticker,
                "ticker.any_of": ",".join(tickers) if tickers else None,
                "ticker.gt": ticker_gt,
                "ticker.gte": ticker_gte,
                "ticker.lt": ticker_lt,
                "ticker.lte": ticker_lte,
                "ex_dividend_date": coerce_date(ex_dividend_date, "ex_dividend_date"),
                "ex_dividend_date.gt": coerce_date(ex_dividend_date_gt, "ex_dividend_date_gt"),
                "ex_dividend_date.gte": coerce_date(ex_dividend_date_gte, "ex_dividend_date_gte"),
                "ex_dividend_date.lt": coerce_date(ex_dividend_date_lt, "ex_dividend_date_lt"),
                "ex_dividend_date.lte": coerce_date(ex_dividend_date_lte, "ex_dividend_date_lte"),
                "frequency": coerce_choice(frequency, DividendFrequency, "frequency"),
                "frequency.gt": frequency_gt,
                "frequency.gte": frequency_gte,
                "frequency.lt": frequency_lt,
                "frequency.lte": frequency_lte,
                "distribution_type.any_of": coerce_choices(distribution_types, DistributionType, "distribution_types"),
                # No `order` parameter here: direction is a suffix on `sort`.
                "sort": coerce_sort(
                    sort, order, Literal["ticker", "ex_dividend_date", "frequency", "distribution_type"]
                ),
                "limit": resolve_page_size(max_results, 5000),
            },
        )
        return self._get_all_pages(
            DIVIDENDS_ENDPOINT,
            params,
            max_results=max_results,
        )

    def get_dividends(
        self,
        *,
        ticker: str | None = None,
        tickers: list[str] | None = None,
        ticker_gt: str | None = None,
        ticker_gte: str | None = None,
        ticker_lt: str | None = None,
        ticker_lte: str | None = None,
        ex_dividend_date: str | date | datetime | None = None,
        ex_dividend_date_gt: str | date | datetime | None = None,
        ex_dividend_date_gte: str | date | datetime | None = None,
        ex_dividend_date_lt: str | date | datetime | None = None,
        ex_dividend_date_lte: str | date | datetime | None = None,
        frequency: DividendFrequency | None = None,
        frequency_gt: int | None = None,
        frequency_gte: int | None = None,
        frequency_lt: int | None = None,
        frequency_lte: int | None = None,
        distribution_types: list[DistributionType] | None = None,
        max_results: int | None = None,
        sort: Literal["ticker", "ex_dividend_date", "frequency", "distribution_type"] = "ticker",
        order: Literal["asc", "desc"] = "asc",
        on_validation_error: Literal["raise", "skip"] | None = None,
    ) -> list[Dividend]:
        """
        Get dividends (across pages, up to `max_results`), validated into `Dividend` models.

        Blocks until every page is fetched, then validates the records that came back.

        Docs: https://massive.com/docs/rest/stocks/corporate-actions/dividends

        Example::

            with MassiveApiSync(api_key="...") as api:
                results = api.dividends_api.get_dividends()

        Args:
            ticker: Stock symbol for the company issuing the dividend
            tickers: Match any of the given ticker symbols.
            ticker_gt: Filter greater than the value.
            ticker_gte: Filter greater than or equal to the value.
            ticker_lt: Filter less than the value.
            ticker_lte: Filter less than or equal to the value.
            ex_dividend_date: Date when the stock begins trading without the dividend value Value must be formatted
                'yyyy-mm-dd'.
            ex_dividend_date_gt: Filter greater than the value. Value must be formatted 'yyyy-mm-dd'.
            ex_dividend_date_gte: Filter greater than or equal to the value. Value must be formatted 'yyyy-mm-dd'.
            ex_dividend_date_lt: Filter less than the value. Value must be formatted 'yyyy-mm-dd'.
            ex_dividend_date_lte: Filter less than or equal to the value. Value must be formatted 'yyyy-mm-dd'.
            frequency: How many times per year this dividend is expected to occur. A value of 0 means the
                distribution is non-recurring or irregular (e.g., special, supplemental, or a one-off dividend).
                Other possible values include 1 (annual), 2 (semi-annual), 3 (trimester), 4 (quarterly), 12
                (monthly), 24 (bi-monthly), 52 (weekly), 104 (bi-weekly), and 365 (daily) depending on the issuer's
                declared or inferred payout cadence. Value must be an integer.
            frequency_gt: Filter greater than the value. Value must be an integer.
            frequency_gte: Filter greater than or equal to the value. Value must be an integer.
            frequency_lt: Filter less than the value. Value must be an integer.
            frequency_lte: Filter less than or equal to the value. Value must be an integer.
            distribution_types: Filter by any of the given distribution types.
            max_results: Maximum total records to return (None means no cap).
            sort: Field to sort by.
            order: Sort direction, "asc" or "desc".
            on_validation_error: Override the config default ("raise" or "skip") for this call.

        Returns:
            A list of `Dividend`, at most `max_results` long.

        Raises:
            ValueError: If an argument is outside the values the API accepts.
            MaxRetriesExceededError: If rate-limit responses persist past `max_retries`.

        """
        records = self.get_dividends_raw(
            ticker=ticker,
            tickers=tickers,
            ticker_gt=ticker_gt,
            ticker_gte=ticker_gte,
            ticker_lt=ticker_lt,
            ticker_lte=ticker_lte,
            ex_dividend_date=ex_dividend_date,
            ex_dividend_date_gt=ex_dividend_date_gt,
            ex_dividend_date_gte=ex_dividend_date_gte,
            ex_dividend_date_lt=ex_dividend_date_lt,
            ex_dividend_date_lte=ex_dividend_date_lte,
            frequency=frequency,
            frequency_gt=frequency_gt,
            frequency_gte=frequency_gte,
            frequency_lt=frequency_lt,
            frequency_lte=frequency_lte,
            distribution_types=distribution_types,
            max_results=max_results,
            sort=sort,
            order=order,
        )
        return self._validate_records(records, Dividend, self._resolve_validation_mode(on_validation_error))
