"""
Splits endpoint (blocking).

Generated by spitzeisen-gen from spec/manifest.yaml. Do not edit; run `mise run codegen`.

Vendor documentation: https://massive.com/docs/rest/stocks/corporate-actions/splits

"""

from datetime import date, datetime
from typing import Any, Literal

from spitzeisen import (
    BaseApi,
    CursorUrl,
    EndpointSpec,
    build_query_params,
    coerce_choices,
    coerce_date,
    coerce_max_results,
    coerce_sort,
    resolve_page_size,
)

from massive_api.models import AdjustmentType, Split

SPLITS_ENDPOINT = EndpointSpec(
    path="/stocks/v1/splits",
    costs={"requests": 1.0},
    pagination=CursorUrl(results_key="results"),
    max_page_size=5000,
)


class SplitsApiSyncBase(BaseApi):
    """
    Generated request layer for the splits endpoint.

    Subclassed by `SplitsApiSync`, which is where any hand-written behaviour
    belongs — this class is regenerated and never edited.
    """

    def get_splits_raw(
        self,
        *,
        ticker: str | None = None,
        ticker_gt: str | None = None,
        ticker_gte: str | None = None,
        ticker_lt: str | None = None,
        ticker_lte: str | None = None,
        execution_date: str | date | datetime | None = None,
        execution_date_gt: str | date | datetime | None = None,
        execution_date_gte: str | date | datetime | None = None,
        execution_date_lt: str | date | datetime | None = None,
        execution_date_lte: str | date | datetime | None = None,
        adjustment_types: list[AdjustmentType] | None = None,
        max_results: int | None = None,
        sort: Literal["ticker", "execution_date"] = "execution_date",
        order: Literal["asc", "desc"] = "desc",
    ) -> list[dict[str, Any]]:
        """
        Fetch splits as raw JSON dicts, without validation.

        See `get_splits` for what each argument means.
        """
        max_results = coerce_max_results(max_results)
        params = build_query_params(
            {
                "ticker": ticker,
                "ticker.gt": ticker_gt,
                "ticker.gte": ticker_gte,
                "ticker.lt": ticker_lt,
                "ticker.lte": ticker_lte,
                "execution_date": coerce_date(execution_date, "execution_date"),
                "execution_date.gt": coerce_date(execution_date_gt, "execution_date_gt"),
                "execution_date.gte": coerce_date(execution_date_gte, "execution_date_gte"),
                "execution_date.lt": coerce_date(execution_date_lt, "execution_date_lt"),
                "execution_date.lte": coerce_date(execution_date_lte, "execution_date_lte"),
                "adjustment_type.any_of": coerce_choices(adjustment_types, AdjustmentType, "adjustment_types"),
                # No `order` parameter here: direction is a suffix on `sort`.
                "sort": coerce_sort(sort, order, Literal["ticker", "execution_date"]),
                "limit": resolve_page_size(max_results, 5000),
            },
        )
        return self._get_all_pages(
            SPLITS_ENDPOINT,
            params,
            max_results=max_results,
        )

    def get_splits(
        self,
        *,
        ticker: str | None = None,
        ticker_gt: str | None = None,
        ticker_gte: str | None = None,
        ticker_lt: str | None = None,
        ticker_lte: str | None = None,
        execution_date: str | date | datetime | None = None,
        execution_date_gt: str | date | datetime | None = None,
        execution_date_gte: str | date | datetime | None = None,
        execution_date_lt: str | date | datetime | None = None,
        execution_date_lte: str | date | datetime | None = None,
        adjustment_types: list[AdjustmentType] | None = None,
        max_results: int | None = None,
        sort: Literal["ticker", "execution_date"] = "execution_date",
        order: Literal["asc", "desc"] = "desc",
        on_validation_error: Literal["raise", "skip"] | None = None,
    ) -> list[Split]:
        """
        Get stock splits (across pages, up to `max_results`), validated into `Split` models.

        Blocks until every page is fetched, then validates the records that came back.

        Docs: https://massive.com/docs/rest/stocks/corporate-actions/splits

        Example::

            with MassiveApiSync(api_key="...") as api:
                results = api.splits_api.get_splits()

        Args:
            ticker: Stock symbol for the company that executed the split
            ticker_gt: Filter greater than the value.
            ticker_gte: Filter greater than or equal to the value.
            ticker_lt: Filter less than the value.
            ticker_lte: Filter less than or equal to the value.
            execution_date: Date when the stock split takes effect. The adjustment is applied overnight. On the
                prior trading day, the post-market session is the last session that shows pre-split prices. On the
                execution date, all trading is already adjusted for the split. This includes the pre-market session.
                Value must be formatted 'yyyy-mm-dd'.
            execution_date_gt: Filter greater than the value. Value must be formatted 'yyyy-mm-dd'.
            execution_date_gte: Filter greater than or equal to the value. Value must be formatted 'yyyy-mm-dd'.
            execution_date_lt: Filter less than the value. Value must be formatted 'yyyy-mm-dd'.
            execution_date_lte: Filter less than or equal to the value. Value must be formatted 'yyyy-mm-dd'.
            adjustment_types: Filter by any of the given adjustment types. Pass a single-element list to match one
                type, e.g. ["forward_split"].
            max_results: Maximum total records to return (None means no cap).
            sort: Field to sort by.
            order: Sort direction, "asc" or "desc".
            on_validation_error: Override the config default ("raise" or "skip") for this call.

        Returns:
            A list of `Split`, at most `max_results` long.

        Raises:
            ValueError: If an argument is outside the values the API accepts.
            MaxRetriesExceededError: If rate-limit responses persist past `max_retries`.

        """
        records = self.get_splits_raw(
            ticker=ticker,
            ticker_gt=ticker_gt,
            ticker_gte=ticker_gte,
            ticker_lt=ticker_lt,
            ticker_lte=ticker_lte,
            execution_date=execution_date,
            execution_date_gt=execution_date_gt,
            execution_date_gte=execution_date_gte,
            execution_date_lt=execution_date_lt,
            execution_date_lte=execution_date_lte,
            adjustment_types=adjustment_types,
            max_results=max_results,
            sort=sort,
            order=order,
        )
        return self._validate_records(records, Split, self._resolve_validation_mode(on_validation_error))
