"""
Tickers endpoint (blocking).

Generated by spitzeisen-gen from spec/manifest.yaml. Do not edit; run `mise run codegen`.

Vendor documentation: https://massive.com/docs/rest/stocks/tickers/all-tickers

"""

from datetime import date, datetime
from typing import Any, Literal

from spitzeisen import (
    BaseApi,
    CursorUrl,
    EndpointSpec,
    Order,
    build_query_params,
    coerce_choice,
    coerce_date,
    coerce_max_results,
    resolve_page_size,
)

from massive_api.models import Market, Ticker

TICKERS_ENDPOINT = EndpointSpec(
    path="/v3/reference/tickers",
    costs={"requests": 1.0},
    pagination=CursorUrl(results_key="results"),
    max_page_size=1000,
)


class TickersApiSyncBase(BaseApi):
    """
    Generated request layer for the tickers endpoint.

    Subclassed by `TickersApiSync`, which is where any hand-written behaviour
    belongs — this class is regenerated and never edited.
    """

    def get_all_tickers_raw(
        self,
        *,
        ticker: str | None = None,
        ticker_type: Literal[
            "CS",
            "ADRC",
            "ADRP",
            "ADRR",
            "UNIT",
            "RIGHT",
            "PFD",
            "FUND",
            "SP",
            "WARRANT",
            "INDEX",
            "ETF",
            "ETN",
            "OS",
            "GDR",
            "OTHER",
            "NYRS",
            "AGEN",
            "EQLK",
            "BOND",
            "ADRW",
            "BASKET",
            "LT",
        ]
        | None = None,
        market: Market | None = None,
        exchange: str | None = None,
        cusip: str | None = None,
        cik: str | None = None,
        date: str | date | datetime | None = None,
        search: str | None = None,
        active: bool = True,
        ticker_gte: str | None = None,
        ticker_gt: str | None = None,
        ticker_lte: str | None = None,
        ticker_lt: str | None = None,
        max_results: int | None = None,
        sort: Literal[
            "ticker",
            "name",
            "market",
            "locale",
            "primary_exchange",
            "type",
            "currency_symbol",
            "currency_name",
            "base_currency_symbol",
            "base_currency_name",
            "cik",
            "composite_figi",
            "share_class_figi",
            "last_updated_utc",
            "delisted_utc",
        ] = "ticker",
        order: Literal["asc", "desc"] = "asc",
    ) -> list[dict[str, Any]]:
        """
        Fetch tickers as raw JSON dicts, without validation.

        See `get_all_tickers` for what each argument means.
        """
        max_results = coerce_max_results(max_results)
        params = build_query_params(
            {
                "ticker": ticker,
                "type": ticker_type,
                "market": coerce_choice(market, Market, "market"),
                "exchange": exchange,
                "cusip": cusip,
                "cik": cik,
                "date": coerce_date(date, "date"),
                "search": search,
                "active": active,
                "ticker.gte": ticker_gte,
                "ticker.gt": ticker_gt,
                "ticker.lte": ticker_lte,
                "ticker.lt": ticker_lt,
                "sort": coerce_choice(
                    sort,
                    Literal[
                        "ticker",
                        "name",
                        "market",
                        "locale",
                        "primary_exchange",
                        "type",
                        "currency_symbol",
                        "currency_name",
                        "base_currency_symbol",
                        "base_currency_name",
                        "cik",
                        "composite_figi",
                        "share_class_figi",
                        "last_updated_utc",
                        "delisted_utc",
                    ],
                    "sort",
                ),
                "order": coerce_choice(order, Order, "order"),
                "limit": resolve_page_size(max_results, 1000),
            },
        )
        return self._get_all_pages(
            TICKERS_ENDPOINT,
            params,
            max_results=max_results,
        )

    def get_all_tickers(
        self,
        *,
        ticker: str | None = None,
        ticker_type: Literal[
            "CS",
            "ADRC",
            "ADRP",
            "ADRR",
            "UNIT",
            "RIGHT",
            "PFD",
            "FUND",
            "SP",
            "WARRANT",
            "INDEX",
            "ETF",
            "ETN",
            "OS",
            "GDR",
            "OTHER",
            "NYRS",
            "AGEN",
            "EQLK",
            "BOND",
            "ADRW",
            "BASKET",
            "LT",
        ]
        | None = None,
        market: Market | None = None,
        exchange: str | None = None,
        cusip: str | None = None,
        cik: str | None = None,
        date: str | date | datetime | None = None,
        search: str | None = None,
        active: bool = True,
        ticker_gte: str | None = None,
        ticker_gt: str | None = None,
        ticker_lte: str | None = None,
        ticker_lt: str | None = None,
        max_results: int | None = None,
        sort: Literal[
            "ticker",
            "name",
            "market",
            "locale",
            "primary_exchange",
            "type",
            "currency_symbol",
            "currency_name",
            "base_currency_symbol",
            "base_currency_name",
            "cik",
            "composite_figi",
            "share_class_figi",
            "last_updated_utc",
            "delisted_utc",
        ] = "ticker",
        order: Literal["asc", "desc"] = "asc",
        on_validation_error: Literal["raise", "skip"] | None = None,
    ) -> list[Ticker]:
        """
        Get every ticker matching the filters, validated into `Ticker` models.

        Blocks until every page is fetched, then validates the records that came back.

        Docs: https://massive.com/docs/rest/stocks/tickers/all-tickers

        Example::

            with MassiveApiSync(api_key="...") as api:
                results = api.tickers_api.get_all_tickers()

        Args:
            ticker: Specify a ticker symbol. Defaults to empty string which queries all tickers.
            ticker_type: Specify the type of the tickers. Find the types that we support via our [Ticker Types
                API](https://massive.com/docs/rest/stocks/tickers/ticker-types). Defaults to empty string which
                queries all types.
            market: Filter by market type. By default all markets are included.
            exchange: Specify the asset's primary exchange Market Identifier Code (MIC) according to [ISO
                10383](https://www.iso20022.org/market-identifier-codes). Defaults to empty string which queries all
                exchanges.
            cusip: Specify the CUSIP code of the asset you want to search for. Find more information about CUSIP
                codes [at their website](https://www.cusip.com/identifiers.html#/CUSIP). Defaults to empty string
                which queries all CUSIPs. Note: Although you can query by CUSIP, due to legal reasons we do not
                return the CUSIP in the response.
            cik: Specify the CIK of the asset you want to search for. Find more information about CIK codes [at
                their website](https://www.sec.gov/edgar/searchedgar/cik.htm). Defaults to empty string which
                queries all CIKs.
            date: Specify a point in time to retrieve tickers available on that date. Defaults to the most recent
                available date.
            search: Search for terms within the ticker and/or company name.
            active: Specify if the tickers returned should be actively traded on the queried date. Default is true.
            ticker_gte: Range by ticker.
            ticker_gt: Range by ticker.
            ticker_lte: Range by ticker.
            ticker_lt: Range by ticker.
            max_results: Maximum total records to return (None means no cap).
            sort: Field to sort by.
            order: Sort direction, "asc" or "desc".
            on_validation_error: Override the config default ("raise" or "skip") for this call.

        Returns:
            A list of `Ticker`, at most `max_results` long.

        Raises:
            ValueError: If an argument is outside the values the API accepts.
            MaxRetriesExceededError: If rate-limit responses persist past `max_retries`.

        """
        records = self.get_all_tickers_raw(
            ticker=ticker,
            ticker_type=ticker_type,
            market=market,
            exchange=exchange,
            cusip=cusip,
            cik=cik,
            date=date,
            search=search,
            active=active,
            ticker_gte=ticker_gte,
            ticker_gt=ticker_gt,
            ticker_lte=ticker_lte,
            ticker_lt=ticker_lt,
            max_results=max_results,
            sort=sort,
            order=order,
        )
        return self._validate_records(records, Ticker, self._resolve_validation_mode(on_validation_error))
