"""
Ticker Events endpoint (awaitable).

Generated by spitzeisen-gen from spec/manifest.yaml. Do not edit; run `mise run codegen`.

Vendor documentation: https://massive.com/docs/rest/stocks/corporate-actions/ticker-events

"""

from typing import Any

from spitzeisen import (
    AsyncBaseApi,
    EndpointSpec,
    NoPagination,
    build_query_params,
    coerce_choice,
)

from massive_api.models import TickerEvents, TickerEventType

TICKER_EVENTS_ENDPOINT = EndpointSpec(
    path="/vX/reference/tickers/{id}/events",
    costs={"requests": 1.0},
    pagination=NoPagination(results_key="results"),
)


class TickerEventsApiBase(AsyncBaseApi):
    """
    Generated request layer for the ticker events endpoint.

    Subclassed by `TickerEventsApi`, which is where any hand-written behaviour
    belongs — this class is regenerated and never edited.
    """

    async def get_ticker_events_raw(
        self,
        ticker_id: str,
        *,
        types: TickerEventType | None = None,
    ) -> dict[str, Any] | None:
        """
        Fetch the raw JSON `results` object, without validation.

        Returns None when the resource does not exist (HTTP 404), which this endpoint treats
        as a routine outcome rather than a failure.
        """
        params = build_query_params(
            {
                "types": coerce_choice(types, TickerEventType, "types"),
            },
        )
        data = await self._request_optional(
            TICKER_EVENTS_ENDPOINT,
            params,
            id=ticker_id,
        )
        if data is None:
            return None
        # A 200 whose envelope lacks the key is a payload the vendor should not have sent.
        # Treated as absent, consistently with this endpoint's `not_found: empty`.
        return data.get("results") or None

    async def get_ticker_events(
        self,
        ticker_id: str,
        *,
        types: TickerEventType | None = None,
    ) -> TickerEvents | None:
        """
        Get the corporate-event history for a ticker, validated into `TickerEvents`.

        Awaits the response, then validates it.

        Docs: https://massive.com/docs/rest/stocks/corporate-actions/ticker-events

        Example::

            async with MassiveApi(api_key="...") as api:
                result = await api.ticker_events_api.get_ticker_events(ticker_id=...)

        Args:
            ticker_id: Identifier of an asset, which can be a Ticker, CUSIP, or Composite FIGI. Specify a case-
                sensitive ticker symbol (e.g. AAPL for Apple Inc). When provided a ticker, events for the entity
                currently represented by that ticker are returned. To find events for entities previously associated
                with a ticker, obtain the relevant identifier using the [Ticker Details
                Endpoint](https://massive.com/docs/rest/stocks/tickers/ticker-overview).
            types: A comma-separated list of the types of event to include. Currently ticker_change is the only
                supported event_type. Leave blank to return all supported event_types.

        Returns:
            A validated `TickerEvents`, or None when the resource does not exist (HTTP 404).
            Raises pydantic.ValidationError on a payload that does not match.


        """
        raw = await self.get_ticker_events_raw(
            ticker_id,
            types=types,
        )
        if raw is None:
            return None
        return TickerEvents.model_validate(raw)
