"""
Ticker Overview endpoint (awaitable).

Generated by spitzeisen-gen from spec/manifest.yaml. Do not edit; run `mise run codegen`.

Vendor documentation: https://massive.com/docs/rest/stocks/tickers/ticker-overview

"""

from datetime import date, datetime
from typing import Any

from spitzeisen import (
    AsyncBaseApi,
    EndpointSpec,
    NoPagination,
    build_query_params,
    coerce_date,
)

from massive_api.models import TickerOverview

TICKER_OVERVIEW_ENDPOINT = EndpointSpec(
    path="/v3/reference/tickers/{ticker}",
    costs={"requests": 1.0},
    pagination=NoPagination(results_key="results"),
)


class TickerOverviewApiBase(AsyncBaseApi):
    """
    Generated request layer for the ticker overview endpoint.

    Subclassed by `TickerOverviewApi`, which is where any hand-written behaviour
    belongs — this class is regenerated and never edited.
    """

    async def get_ticker_overview_raw(
        self,
        ticker: str,
        *,
        date: str | date | datetime | None = None,
    ) -> dict[str, Any] | None:
        """
        Fetch the raw JSON `results` object, without validation.

        Returns None when the resource does not exist (HTTP 404), which this endpoint treats
        as a routine outcome rather than a failure.
        """
        params = build_query_params(
            {
                "date": coerce_date(date, "date"),
            },
        )
        data = await self._request_optional(
            TICKER_OVERVIEW_ENDPOINT,
            params,
            ticker=ticker,
        )
        if data is None:
            return None
        # A 200 whose envelope lacks the key is a payload the vendor should not have sent.
        # Treated as absent, consistently with this endpoint's `not_found: empty`.
        return data.get("results") or None

    async def get_ticker_overview(
        self,
        ticker: str,
        *,
        date: str | date | datetime | None = None,
    ) -> TickerOverview | None:
        """
        Get detailed information for a single ticker, validated into a `TickerOverview`.

        Awaits the response, then validates it.

        Docs: https://massive.com/docs/rest/stocks/tickers/ticker-overview

        Example::

            async with MassiveApi(api_key="...") as api:
                result = await api.ticker_overview_api.get_ticker_overview(ticker=...)

        Args:
            ticker: Specify a case-sensitive ticker symbol. For example, AAPL represents Apple Inc.
            date: Specify a point in time to get information about the ticker available on that date. When
                retrieving information from SEC filings, we compare this date with the period of report date on the
                SEC filing. For example, consider an SEC filing submitted by AAPL on 2019-07-31, with a period of
                report date ending on 2019-06-29. That means that the filing was submitted on 2019-07-31, but the
                filing was created based on information from 2019-06-29. If you were to query for AAPL details on
                2019-06-29, the ticker details would include information from the SEC filing. Defaults to the most
                recent available date.

        Returns:
            A validated `TickerOverview`, or None when the resource does not exist (HTTP 404).
            Raises pydantic.ValidationError on a payload that does not match.


        """
        raw = await self.get_ticker_overview_raw(
            ticker,
            date=date,
        )
        if raw is None:
            return None
        return TickerOverview.model_validate(raw)
