"""
Rate-limit buckets for massive.

Generated by spitzeisen-gen from spec/manifest.yaml. Do not edit; run `mise run codegen`.

These are **defaults**. An API that reports its real allowance at runtime — from a metadata
endpoint or from rate-limit response headers — overrides `capacity` and `initial_tokens` when
its limiter builds the buckets. That has to happen at construction: the underlying buckets
validate both up front and expose no setters.
"""

from datetime import timedelta

from spitzeisen import BucketSpec, LimitSet

LIMITS: LimitSet = {
    "requests": BucketSpec(
        capacity=100.0,
        refill=timedelta(seconds=1.0),
        smooth=True,
        align=None,
        max_sleep=60.0,
        expiry=120,
    ),
}
