"""
The models a caller receives, and the value sets they may pass.

Most are generated from the vendor's OpenAPI document (`_generated.py`, regenerated by
`mise run codegen`); `TickerOverview` is hand-written because it flattens nested objects.
Both are re-exported here under the names this client has always used, so which side a model
comes from is an implementation detail rather than part of the public API.

The parameter `Literal`s are re-exported too: generated endpoint modules import the types they
validate against from this module.
"""

from massive_api.models._generated import (
    Bar,
    Dividend,
    Split,
    Ticker,
    TickerChange,
    TickerEvents,
)
from massive_api.models._generated import Events as TickerEvent
from massive_api.models._manual import TickerOverview
from massive_api.params import (
    AdjustmentType,
    DistributionType,
    DividendFrequency,
    DividendSortField,
    Locale,
    Market,
    Order,
    SplitSortField,
    TickerEventType,
    TickerSortField,
    Timespan,
)

__all__ = (
    "AdjustmentType",
    "Bar",
    "DistributionType",
    "Dividend",
    "DividendFrequency",
    "DividendSortField",
    "Locale",
    "Market",
    "Order",
    "Split",
    "SplitSortField",
    "Ticker",
    "TickerChange",
    "TickerEvent",
    "TickerEventType",
    "TickerEvents",
    "TickerOverview",
    "TickerSortField",
    "Timespan",
)
