# generated by datamodel-codegen:
#   filename:  pruned.json
#   timestamp: 2026-08-16T17:01:27+00:00

from __future__ import annotations

from datetime import date as date_aliased
from typing import Annotated, Literal

from pydantic import AwareDatetime, Field
from spitzeisen import VendorModel

from massive_api.types import EpochMillis


class Dividend(VendorModel):
    cash_amount: float
    """
    Original dividend amount per share in the specified currency
    """
    currency: str | None = None
    """
    Currency code for the dividend payment (e.g., USD, CAD)
    """
    declaration_date: date_aliased | None = None
    """
    Date when the company officially announced the dividend
    """
    distribution_type: Literal["recurring", "special", "supplemental", "irregular", "unknown"]
    """
    Classification describing the nature of this dividend's recurrence pattern: recurring (paid on a regular schedule), special (one-time or commemorative), supplemental (extra beyond the regular schedule), irregular (unpredictable or non-recurring), unknown (cannot be classified from available data)
    """
    ex_dividend_date: date_aliased
    """
    Date when the stock begins trading without the dividend value
    """
    frequency: int | None = None
    """
    How many times per year this dividend is expected to occur. A value of 0 means the distribution is non-recurring or irregular (e.g., special, supplemental, or a one-off dividend). Other possible values include 1 (annual), 2 (semi-annual), 3 (trimester), 4 (quarterly), 12 (monthly), 24 (bi-monthly), 52 (weekly), 104 (bi-weekly), and 365 (daily) depending on the issuer's declared or inferred payout cadence.
    """
    historical_adjustment_factor: float | None = None
    """
    Cumulative adjustment factor used to offset dividend effects on historical prices. To adjust a historical price for dividends: for a price on date D, find the first dividend whose `ex_dividend_date` is after date D and multiply the price by that dividend's `historical_adjustment_factor`.
    """
    id: str | None = None
    """
    Unique identifier for each dividend record
    """
    pay_date: date_aliased | None = None
    """
    Date when the dividend payment is distributed to shareholders
    """
    record_date: date_aliased | None = None
    """
    Date when shareholders must be on record to be eligible for the dividend payment
    """
    split_adjusted_cash_amount: float | None = None
    """
    Dividend amount adjusted for stock splits that occurred after the dividend was paid, expressed on a current share basis
    """
    ticker: str
    """
    Stock symbol for the company issuing the dividend
    """


class StocksV1DividendsGetResponse(VendorModel):
    next_url: str | None = None
    """
    If present, this value can be used to fetch the next page.
    """
    request_id: str
    """
    A request id assigned by the server.
    """
    results: list[Dividend]
    """
    The results for this request.
    """
    status: Literal["OK"]
    """
    The status of this request's response.
    """


class StocksV1DividendsGetResponse1(VendorModel):
    error: str
    """
    A message describing the source of the error.
    """
    request_id: str
    """
    A request id assigned by the server.
    """
    status: Literal["ERROR"]
    """
    The status of this request's response.
    """


class Split(VendorModel):
    adjustment_type: Literal["forward_split", "reverse_split", "stock_dividend"]
    """
    Classification of the share-change event. Possible values include: forward_split (share count increases), reverse_split (share count decreases), stock_dividend (shares issued as a dividend)
    """
    execution_date: date_aliased
    """
    Date when the stock split takes effect. The adjustment is applied overnight. On the prior trading day, the post-market session is the last session that shows pre-split prices. On the execution date, all trading is already adjusted for the split. This includes the pre-market session.
    """
    historical_adjustment_factor: Annotated[float | None, Field(...)]
    """
    Cumulative adjustment factor used to offset split effects on historical prices. To adjust a historical price for splits: for a price on date D, find the first split whose `execution_date` is after date D and multiply the unadjusted price by the `historical_adjustment_factor`.
    """
    id: Annotated[str | None, Field(...)]
    """
    Unique identifier for each stock split event
    """
    split_from: float
    """
    Denominator of the split ratio (old shares)
    """
    split_to: float
    """
    Numerator of the split ratio (new shares)
    """
    ticker: str
    """
    Stock symbol for the company that executed the split
    """


class StocksV1SplitsGetResponse(VendorModel):
    next_url: str | None = None
    """
    If present, this value can be used to fetch the next page.
    """
    request_id: str
    """
    A request id assigned by the server.
    """
    results: list[Split]
    """
    The results for this request.
    """
    status: Literal["OK"]
    """
    The status of this request's response.
    """


class StocksV1SplitsGetResponse1(VendorModel):
    error: str
    """
    A message describing the source of the error.
    """
    request_id: str
    """
    A request id assigned by the server.
    """
    status: Literal["ERROR"]
    """
    The status of this request's response.
    """


class Bar(VendorModel):
    close: Annotated[float, Field(alias="c")]
    """
    The close price for the symbol in the given time period.
    """
    high: Annotated[float, Field(alias="h")]
    """
    The highest price for the symbol in the given time period.
    """
    low: Annotated[float, Field(alias="l")]
    """
    The lowest price for the symbol in the given time period.
    """
    transactions: Annotated[int | None, Field(alias="n")] = None
    """
    The number of transactions in the aggregate window.
    """
    open: Annotated[float, Field(alias="o")]
    """
    The open price for the symbol in the given time period.
    """
    otc: bool | None = None
    """
    Whether or not this aggregate is for an OTC ticker. This field will be left off if false.
    """
    timestamp: Annotated[EpochMillis, Field(alias="t")]
    """
    The Unix millisecond timestamp for the start of the aggregate window.
    """
    volume: Annotated[float, Field(alias="v")]
    """
    The trading volume of the symbol in the given time period.
    """
    vwap: Annotated[float | None, Field(alias="vw")] = None
    """
    The volume weighted average price.
    """


class V2AggsTickerStocksTickerRangeMultiplierTimespanFromToGetResponse(VendorModel):
    ticker: str
    """
    The exchange symbol that this item is traded under.
    """
    adjusted: bool
    """
    Whether or not this response was adjusted for splits.
    """
    queryCount: int
    """
    The number of aggregates (minute or day) used to generate the response.
    """
    request_id: str
    """
    A request id assigned by the server.
    """
    resultsCount: int
    """
    The total number of results for this request.
    """
    status: str
    """
    The status of this request's response.
    """
    results: list[Bar] | None = None
    """
    An array of results containing the requested data.
    """
    next_url: str | None = None
    """
    If present, this value can be used to fetch the next page of data.
    """


class Ticker(VendorModel):
    active: bool
    """
    Whether or not the asset is actively traded. False means the asset has been delisted.
    """
    base_currency_name: str | None = None
    """
    The name of the currency that this asset is priced against.
    """
    base_currency_symbol: str | None = None
    """
    The ISO 4217 code of the currency that this asset is priced against.
    """
    cik: str | None = None
    """
    The CIK number for this ticker. Find more information [here](https://en.wikipedia.org/wiki/Central_Index_Key).
    """
    composite_figi: str | None = None
    """
    The composite OpenFIGI number for this ticker. Find more information [here](https://www.openfigi.com/about/figi)
    """
    currency_name: str | None = None
    """
    The name of the currency that this asset is traded with.
    """
    currency_symbol: str | None = None
    """
    The ISO 4217 code of the currency that this asset is traded with.
    """
    delisted_utc: AwareDatetime | None = None
    """
    The last date that the asset was traded.
    """
    last_updated_utc: AwareDatetime | None = None
    """
    The information is accurate up to this time.
    """
    locale: Literal["us", "global"] | None = None
    """
    The locale of the asset.
    """
    market: Literal["stocks", "crypto", "fx", "otc", "indices"] | None = None
    """
    The market type of the asset.
    """
    name: str | None = None
    """
    The name of the asset. For stocks/equities this will be the companies registered name. For crypto/fx this will be the name of the currency or coin pair.
    """
    primary_exchange: str | None = None
    """
    The ISO code of the primary listing exchange for this asset.
    """
    share_class_figi: str | None = None
    """
    The share Class OpenFIGI number for this ticker. Find more information [here](https://www.openfigi.com/about/figi)
    """
    ticker: str
    """
    The exchange symbol that this item is traded under.
    """
    type: str | None = None
    """
    The type of the asset. Find the types that we support via our [Ticker Types API](https://massive.com/docs/rest/stocks/tickers/ticker-types).
    """


class V3ReferenceTickersGetResponse(VendorModel):
    count: int | None = None
    """
    The total number of results for this request.
    """
    next_url: str | None = None
    """
    If present, this value can be used to fetch the next page of data.
    """
    request_id: str | None = None
    """
    A request id assigned by the server.
    """
    results: list[Ticker] | None = None
    """
    An array of tickers that match your query.

    Note: Although you can query by CUSIP, due to legal reasons we do not return the CUSIP in the response.
    """
    status: str | None = None
    """
    The status of this request's response.
    """


class TickerChange(VendorModel):
    """
    Details about a ticker change
    """

    ticker: str | None = None
    """
    A ticker symbol
    """


class Events(VendorModel):
    date: date_aliased
    """
    The date the event took place
    """
    type: Annotated[str, Field(alias="event_type")]
    """
    The type of historical event for the asset
    """
    ticker_change: TickerChange | None = None
    """
    Details about a ticker change
    """


class TickerEvents(VendorModel):
    """
    Contains the requested event data for the specified ticker.
    """

    events: list[Events]
    """
    An array of event containing the requested data.
    """
    name: str
    """
    The name of the asset.
    """


class VXReferenceTickersIdEventsGetResponse(VendorModel):
    request_id: str | None = None
    """
    A request id assigned by the server.
    """
    results: Annotated[TickerEvents | None, Field(title="TickerEvents")] = None
    """
    Contains the requested event data for the specified ticker.
    """
    status: str | None = None
    """
    The status of this request's response.
    """
